# Discovery Server Access
spring.cloud.loadbalancer.ribbon.enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
microservices:
  proxy:
    zuul:
      url: http://192.168.1.111:9000/api/
  config:
    swagger:
      isSwaggerEnabled : true
    authentication:
      login:
        header-auth: Basic YWRtaW46MTIzNDU2
        path: /oauth/token
        username: '{cipher}a0e86dafb2c8fd33bca2d0ac09df6af7144c89383cc0387a8e4eb73ee1ede71a4e8375822095ff7ea637580b6b01b909'
        password: '{cipher}e6ed92bc1d3d4dd84d69568162de0117febb084163b29ba55b40516da7fe10ac'
encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lofje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lofje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64LoDSADASGD1
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev, debug 
  application:
    sign-in-key: 'MIICWwIBAAKBgGtQ4ylb/cc2fez21oSEisr95JdurRnz/xcW4dja3zePJmRp7sFjYqv52x4Hc+n9YSeOYMGZ2QwzItDkBPzyDOVCE/eTX2a3fEYqNGiNWUTYJvtywM6SGHvgtJ97w4sL4/YlAk6V1xdO6Ea+89IxuHrKFiCDoGmMrtdjyz7JDmmHAgMBAAECgYAiE+Z+vLqCpxgnxl5qaFhWi3cqazfGtQd9AoQnQ6F8WBW97zGk8XVk3Quqpn01gYN3dyvcbolQ6XAV20KGPCrBumubAUAXJjoxmmK8RmWSc5EJpvaaNwQ35Jp2lxtL0VzLQYVxuLWRaokvNogPQUEIjo17W8/kTqsZmukFGg6p2QJBAM8n7FXF+kg4fTTTaQ=='
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://192.168.1.111:8760/eureka/