eureka:
  datacenter: centro-datos-local
  environment: desarrollo

---

spring:
  profiles: eureka-server-instance-1

server:
  port: ${SERVER_PORT:8760}
eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URL}


---


spring:
  profiles: eureka-server-instance-2

server:
  port: ${SERVER_PORT:8761}
eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URL}